(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function t(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(s){if(s.ep)return;s.ep=!0;const n=t(s);fetch(s.href,n)}})();const m=(o,e)=>{try{const t=JSON.stringify(e);localStorage.setItem(o,t)}catch(t){console.log(t)}},a=o=>{try{const e=localStorage.getItem(o);return e===null?void 0:JSON.parse(e)}catch(e){console.log(e)}},g=o=>{try{localStorage.removeItem(o)}catch(e){console.log(e)}},c={themeToggleBtn:document.querySelector(".theme-toggle-button"),headerForm:document.querySelector(".header-form"),taskInput:document.querySelector(".header-form-input"),headerFormBtn:document.querySelector(".header-form-btn"),emptyList:document.querySelector(".empty-list"),tasksList:document.querySelector(".tasks-list"),filterBtnAll:document.querySelector(".filter-btn-all"),allCount:document.querySelector(".all-count"),filterBtnCompleted:document.querySelector(".filter-btn-completed"),completedCount:document.querySelector(".completed-count"),filterBtnActive:document.querySelector(".filter-btn-active"),activeCount:document.querySelector(".active-count"),clearBtn:document.querySelector(".clear-btn")},u=o=>{const e=o.map(t=>`
      <li class="task-list-item ${t.completed?"completed":""}">
      <p>${t.discr}</p>
      <div class="list-btn">
      <button class="task-list-btn done-btn ${t.completed?"completed":""}" data-id="${t.id}">✓</button>
        <button class="task-list-btn delete-btn" data-id="${t.id}">⨉</button>
      </div>
    </li>`).join("");c.tasksList.insertAdjacentHTML("beforeend",e)},h=()=>{c.tasksList.innerHTML=""},f=document.getElementById("moonIcon"),p=document.getElementById("sunIcon"),L=o=>{o==="light"?(document.body.classList.add("theme-light"),document.body.classList.remove("theme-dark"),p.classList.add("hidden"),f.classList.remove("hidden")):(document.body.classList.remove("theme-light"),document.body.classList.add("theme-dark"),p.classList.remove("hidden"),f.classList.add("hidden"))},k=localStorage.getItem("theme")||"light";L(k);const v=()=>{const o=document.body.classList.contains("theme-light");let e;o?e="dark":e="light",L(e),localStorage.setItem("theme",e)};c.themeToggleBtn.addEventListener("click",v);const l=()=>{const o=a("tasks")||[],e=o.length,t=o.filter(s=>s.completed).length,r=e-t;c.allCount.textContent=e,c.completedCount.textContent=t,c.activeCount.textContent=r},b=()=>{const o=a("tasks")||[],e=o.filter(s=>!s.completed),t=o.filter(s=>s.completed),r=[...e,...t];r.length>0?(c.emptyList.classList.add("hidden"),u(r)):c.emptyList.classList.remove("hidden"),l()},y=o=>{const e=a("tasks")||[];let t=[];switch(o){case"completed":t=e.filter(n=>n.completed);break;case"active":t=e.filter(n=>!n.completed);break;default:t=e;const r=e.filter(n=>!n.completed),s=e.filter(n=>n.completed);t=[...r,...s]}h(),t.length>0?(c.emptyList.classList.add("hidden"),u(t)):c.emptyList.classList.remove("hidden")};b();l();const S=o=>{o.preventDefault();const e=c.taskInput.value.trim();if(e==="")return;const t={id:crypto.randomUUID(),discr:e,completed:!1},r=a("tasks")||[];r.push(t),m("tasks",r),c.emptyList.classList.add("hidden"),u([t]),l(),c.headerForm.reset()},T=o=>{const e=o.target,t=e.closest(".task-list-item"),r=e.dataset.id;let s=a("tasks")||[];if(e.classList.contains("delete-btn")&&(s=s.filter(n=>n.id!==r),m("tasks",s),l(),t&&t.remove(),s.length===0&&c.emptyList.classList.remove("hidden")),e.classList.contains("done-btn")){s=s.map(d=>d.id===r?{...d,completed:!d.completed}:d),m("tasks",s),l();const n=document.querySelector(".filter-btn.active"),i=(n==null?void 0:n.dataset.filter)||"all";y(i)}},C=()=>{h(),g("tasks"),l(),c.emptyList.classList.remove("hidden")},I=o=>{const e=o.target.closest("button[data-filter]");if(!e)return;document.querySelectorAll(".filter-btn").forEach(r=>r.classList.remove("active")),e.classList.add("active");const t=e.dataset.filter;y(t)};c.filterBtnAll.parentElement.parentElement.addEventListener("click",I);c.headerForm.addEventListener("submit",S);c.tasksList.addEventListener("click",T);c.clearBtn.addEventListener("click",C);
//# sourceMappingURL=index.js.map
